name: Starter Sample
version: 0.1.3
description: Runnable starter stack, copy to create a new stack
license: Apache-2.0
language: java
maintainers: 
  - name: Sunwon Yoon
    email: zeradoon@sk.com
    github-id: zeradoon
default-template: simple
